name: Build Flutter Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # ဒီနေရာမှာ GitHub က သုံးမယ့် Flutter ဗားရှင်းကို နောက်ဆုံးထွက် Stable ဖြစ်အောင် မြှင့်လိုက်ပါတယ်
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get Flutter Packages
      run: flutter pub get

    - name: Build Release APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Burmese-AI-Brain-APK
        path: build/app/outputs/flutter-apk/app-release.apk
